version: '3'

services:

  # PHP
  php:
    image: php:7.4-fpm
    container_name: php
    # Dockerfile内のコマンドを実行させたいときはbuld指定をする（context:とdockerfile:でパスとファイル名を別々で指定できる様子）
    # build: ./_docker/php
    volumes:
    - ./public:/var/www/html
    - ./_docker/php/php.ini:/usr/local/etc/php/php.ini

  # nginx
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
    - php
    ports:
    - 8080:80
    volumes:
    - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./public:/var/www/html
    - ./public:/usr/share/nginx/html
